In [1]:
import numpy as np
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [2]:
type(test_array[3])

numpy.float64

In [7]:
test_array = np.array([1,4,5,'8'],float)
print(test_array)

[1. 4. 5. 8.]


In [8]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [9]:
print(test_array.dtype)

float64


In [10]:
print(test_array.shape)

(4,)


In [11]:
matrix=[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [12]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [13]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]
np.array(tensor_rank3, int).ndim

3

In [14]:
np.array(tensor_rank3, int).size

48

## dtype

In [15]:
np.array([[1,2,3.5], [4,5,6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.array([[1,2,3.5], [4,5,6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [17]:
np.array([[1,2,3.5], [4,5,6.5]])

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [18]:
import sys
np.array([[1,2,3.5], [4,5,6.5]], dtype=np.float64).itemsize

8

In [19]:
np.array([[1,2,3.5], [4,5,6.5]], dtype=np.float32).itemsize

4

## 배열 구조 다루기 

In [21]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [22]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [23]:
x= np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
x.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [27]:
# -1을 통한 자동 설정
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

## 인덱싱과 슬라이싱 

In [30]:
x = np.array([[1,2,3], [4.5,5,6]],int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
x[0][0]

1

In [32]:
x[0,2]

3

In [33]:
x[0,1]= 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [34]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]],int)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
x[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [36]:
x[1,1:3]

array([7, 8])

In [40]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [43]:
x =np.array(range(15), int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [45]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

## 배열 생성 함수 

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [50]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [51]:
np.ones(shape=(5,2),dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [52]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [53]:
np.empty(shape=(2,4), dtype=np.float32)

array([[2.9965666e+32, 4.3219420e+27, 6.9492781e+22, 4.9995069e-14],
       [1.3563128e-19, 1.1767972e+27, 1.2733610e-14, 3.7293091e-08]],
      dtype=float32)

In [54]:
x= np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [56]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [58]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [59]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [60]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
np.diag(matrix)

array([0, 4, 8])

In [63]:
np.diag(matrix, k=1)

array([1, 5])

## 통계 분석 함수 

In [64]:
np.random.uniform(0,5,10)

array([4.28490425, 1.60985438, 3.54540942, 3.98805711, 1.45512751,
       2.75156621, 3.73347651, 3.91518436, 2.56445794, 3.02361375])

In [65]:
np.random.normal(0,2,10)

array([ 2.39521263,  0.35208542,  2.10004245, -1.94212539, -3.48778019,
       -1.49124319, -3.93359289, -0.13694502,  1.41556245,  0.71235024])