## 연산 함수 

In [1]:
import numpy as np
test_array = np.arange(1,11)
test_array.sum()

55

In [3]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [5]:
test_array.sum(axis=1)

array([10, 26, 42])

In [6]:
test_array = np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [7]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [8]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [9]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [10]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [12]:
test_array.std()

3.452052529534663

In [13]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [15]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

## 연결 함수 

In [16]:
v1= np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [18]:
v2

array([[4],
       [5],
       [6]])

In [19]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
v1= np.array([[1,2,3]])
v2=np.array([[4,5,6]])
np.concatenate((v1,v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [23]:
v2

array([[5],
       [6]])

In [24]:
np.concatenate((v1,v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## 사칙연산 함수 

In [26]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [32]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [33]:
# 내적 연산

x_1=np.arange(1,7).reshape(2,3)
x_2=np.arange(1,7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [36]:
x_2.dot(x_1)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [37]:
# 브로드캐스팅

x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
x+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [39]:
x-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [43]:
x//3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]], dtype=int32)

In [41]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [44]:
# 확장된 브로드캐스팅 연산

x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
v =np.arange(10,40,10)
v

array([10, 20, 30])

In [46]:
v=np.arange(10,40,10)

In [47]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])