In [1]:
#1.1 브로드캐스팅 비교 연산
import numpy as np
x =np.array([4,3,2,6,8,5])
x>3

array([ True, False, False,  True,  True,  True])

In [2]:
#1.2 요소별 비교연산
x = np.array([1,3,0])
y = np.array([2,1,7])
x>y

array([False,  True, False])

In [3]:
#2.1 all과 any

x=np.array([4,6,7,3,2])
(x>3)

array([ True,  True,  True, False, False])

In [4]:
(x>3).all()

False

In [5]:
(x>3).any()

True

In [6]:
(x<10).all()

True

In [7]:
(x<10).any()

True

In [8]:
(x>10).any()

False

In [9]:
#2.2. 인덱스 반환 함수

x = np.array([4,6,7,3,2])
x>5

array([False,  True,  True, False, False])

In [10]:
np.where(x>5)

(array([1, 2], dtype=int64),)

In [11]:
x = np.array([4,6,7,3,2])
np.where(x>5,10,20)

array([20, 10, 10, 20, 20])

In [12]:
#2.3 정렬된 값의 인덱스를 반환

x = np.array([4,6,7,3,2])
np.argsort(x)

array([4, 3, 0, 1, 2], dtype=int64)

In [13]:
#3.1 불린 인덱스

x = np.array([4,6,7,3,2])
x>3

array([ True,  True,  True, False, False])

In [14]:
cond = x>3
x[cond]

array([4, 6, 7])

In [15]:
x.shape

(5,)

In [16]:
cond.shape

(5,)

In [17]:
# 3.2 팬시 인덱스

x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2,],int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [18]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [19]:
x = np.array([[1,4], [9,16]],int)
a = np.array([0,1,1,1,0,0], int)
b = np.array([0,0,0,1,1,1],int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])