In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
!pip install pandas

In [4]:
import pandas as pd

In [3]:
data=[1,2,3]
arr = np.array(data)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
data = [1,2,3]

result = []
for i in data:
    result.append(i*10)
print(result)

[10, 20, 30]


In [5]:
arr = np.array([1,2,3])
result = arr*10
print(result)

[10 20 30]


In [6]:
data2d = [
[1,2,3],
[4,5,6],
[7,8,9]
]

print(data2d[0])

[1, 2, 3]


In [7]:
data2d = [
[1,2,3],
[4,5,6],
[7,8,9]
]

arr = np.array(data2d)
print(arr[:, 0])

[1 4 7]


In [8]:
data1 = [1,2,3,4]

arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
data2 = [
    [1,2],
    [3,4]
]
arr2 = np.array(data2)
print(arr2)
print(type(arr2))
print(type(arr2[0]))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 2)
2
int32


In [13]:
print(arr1.shape)

(4,)


In [14]:
data = [
    [1],
    [2],
    [3],
    [4]
]
c = np.array(data)
print(c.shape)

(4, 1)


In [15]:
print(np.zeros(3))

[0. 0. 0.]


In [16]:
print(np.ones(3))

[1. 1. 1.]


In [18]:
size=(3,4)
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
print(np.arange(5))
print(np.arange(1,5))
print(np.arange(1,5,2))

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [24]:
ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2,3)
print(ndarr2)

[[0 1 2]
 [3 4 5]]


In [26]:
arr = np.array([1,2,3], dtype=np.uint8)
print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


In [27]:
arr = arr.astype('int8')
print(arr.dtype)

int8


In [28]:
a = np.array([0,255], dtype=np.uint8)
b = a.astype('int8')
print(a)
print(b)

[  0 255]
[ 0 -1]


In [29]:
a16 = np.array([1.333333 ], dtype=np.float16)
a32 = np.array([1.333333], dtype=np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [30]:
a16 = np.array([1.0], dtype=np.float16)
a32 = np.array([1.0], dtype=np.float32)
print(a16/3)
print(a32/3)

[0.3333]
[0.33333334]


In [31]:
print(np.nan, type(np.nan))
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [32]:
arr = np.array([-1,2-3])
print(arr/0)

[-inf -inf]


C:\Users\USER\AppData\Local\Temp/ipykernel_15400/207593033.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print(arr/0)


In [33]:
print(np.nan, type(np.nan))
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [34]:
arr = np.array([-1,2-3])
print(arr/0)

[-inf -inf]


C:\Users\USER\AppData\Local\Temp/ipykernel_15400/207593033.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print(arr/0)


In [35]:
arr = np.array([-1,2,-3])
print(arr + np.nan)
print(arr+np.inf)

[nan nan nan]
[inf inf inf]


In [5]:
arr = np.arange(4)
print(arr[0])

0


In [6]:
arr = np.arange(4).reshape(2,2)
print (arr[0])

[0 1]


In [7]:
print(arr[0][0])

0


In [8]:
print(arr[0,0])

0


In [9]:
a= np.arange(10000).reshape(100,100)
%timeit a[0,50]

64.1 ns ± 0.836 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [11]:
a =np.arange(10000).reshape(100,100)
%timeit a[0][50]

134 ns ± 0.834 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [12]:
arr = np.arange(4)
print(arr[ : 2])

[0 1]


In [13]:
target = [0,2]
print(arr[ target])

[0 2]


In [14]:
print(arr[[0,2]])

[0 2]


In [15]:
arr = np.arange(20).reshape(4,5)
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
result = []
for row in arr:
    row_01 = [ row[0], row[1]]
    result.append(row_01)

In [17]:
print(arr[ :, :2])

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]


In [18]:
print(arr[ 1:4, 2:5])
print(arr[1: , 2: ])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [19]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a+b)
print(a*b)
print(a%b)

[3 5 7]
[ 2  6 12]
[1 2 3]


In [20]:
print(a+3)

[4 5 6]


In [21]:
high = [92700, 92400, 92100, 94300, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low

In [22]:
print(arr_diff)

[2700 1300  400 2200 1400]


In [24]:
arr_high_x3 = arr_high*3
arr_low_x2 = arr_low*2
print(arr_high_x3+arr_low_x2)

[458100 459400 459700 467100 458700]


In [25]:
avg =(arr_high*3)+(arr_low*2)

In [26]:
print(avg)

[458100 459400 459700 467100 458700]


In [27]:
data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91000, 91700, 92100, 90900]
]
arr = np.array(data)

In [28]:
print(arr[0]*3+arr[1]*2)

[458100 459200 459700 467100 458700]


In [29]:
weight = np.array([3,2]).reshape(2,1)
print((weight*arr).sum(axis=0))

[458100 459200 459700 467100 458700]


In [3]:
arr = np.array([10,20,30])
print(arr>10)

[False  True  True]


In [4]:
arr = np.array([10,20,30])

In [5]:
cond = [False, True, True]
print(arr[cond])

[20 30]


In [6]:
arr = np.array([10,20,30])
print(arr[[False, True, True]])

[20 30]


In [7]:
arr = np.array([10,20,30])
cond = arr>10
print(arr[cond])

[20 30]


In [8]:
print(arr[arr>10])

[20 30]


In [10]:
cond.all()
cond.any()

True

In [12]:
arr = np.array([10,20,30])
cond0 = arr>10
cond1 = arr<30
print(arr[cond0&cond1])

[20]


In [13]:
arr = np.array([10,20,30])
print(arr[(arr>10)&(arr<30)])

[20]


In [14]:
arr = np.array([10,20,30])
cond = arr>10
arr[cond] = 1
arr[~cond] =0
print(arr)

[0 1 1]


In [15]:
arr = np.array([10,20,30])
arr = np.where(arr>10,1,0)
print(arr)

[0 1 1]


In [16]:
cond = arr>10
arr[cond] = arr[cond] +10
arr[~cond] = arr[~cond] -10

In [17]:
arr = np.where(arr>10, arr+10, arr-10)

In [18]:
lge = np.array([93000,82400,99100,81000,72300])

In [20]:
result = lge[lge<=85000]
print(result)

[82400 81000 72300]


In [22]:
arr =np.arange(8).reshape(4,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [23]:
print(arr.sum(axis=0))

[12 16]


In [24]:
print(arr.sum(axis=1))

[ 1  5  9 13]


In [27]:
np.random.randint(3)

0

In [29]:
np.random.randint(46, size=5)


array([35, 41, 17,  2, 36])

In [31]:
np.random.randint(46, size=(2,5))

array([[11, 29, 42, 18, 29],
       [37, 45, 40, 15, 29]])

In [32]:
x =np.linspace(0, 10, 3)
print(x)

[ 0.  5. 10.]


In [33]:
y =x**2

In [34]:
a= np.arange(4)
b = np.arange(4, 8)
c= np.vstack([a,b])
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [38]:
from pandas import Series

data = [10,20,30]
s = Series(data)
print(s)

0    10
1    20
2    30
dtype: int64


In [39]:
from pandas import Series
import numpy as np

data = np.arange(5)
s = Series(data)
print(s)

0    0
1    1
2    2
3    3
4    4
dtype: int32


In [40]:
data = ["시가","고가"]
s = Series(data)
print(s)

0    시가
1    고가
dtype: object


In [41]:
s = Series(['samsung',81000])
print(s)

0    samsung
1      81000
dtype: object


In [42]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data)
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [44]:
data = [1000, 2000, 3000]
s = Series(data)
s.index = ["메로나", "구구콘", "하겐다즈"]
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [47]:
data = [1000,2000,3000]
index = ["메로나", "구구콘", "하겐다즈"]

s = Series(data=data, index=index)

In [48]:
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [49]:
s= Series(data, index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [50]:
s2= s.reindex(["메로나","비비빅","구구콘"])
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [51]:
print(s2.fillna(0))

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [52]:
s2 = s.reindex(["메로나", "비비빅", "구구콘"], fill_value=0)

In [53]:
print(s2)

메로나    1000
비비빅       0
구구콘    2000
dtype: int64


In [54]:
price = [42500, 42550, 41800, 42550, 42650]
date = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
S = Series(price, date)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [55]:
data = {
    "2019-05-31" :42500,
    "2019-05-30" :42550,
    "2019-05-29" :41800,
    "2019-05-28" :42550,
    "2019-05-27" :42650
}
s = Series(data)

In [56]:
print(s.index)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='object')


In [57]:
print(s.index.dtype)

object


In [58]:
print(s.values)

[42500 42550 41800 42550 42650]


In [1]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data = data)

In [2]:
print(s.iloc[0])

1000


In [3]:
print(s.iloc[1])

2000


In [4]:
print(s.iloc[2])

3000


In [6]:
print(s.iloc[-1])

3000


In [7]:
print(s.loc[1])

2000


In [9]:
print(s.loc[2])


3000


In [11]:
print(s.loc[-1])

KeyError: -1

In [13]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)

print(s.iloc[0])
print(s.loc['메로나'])


1000
1000


In [14]:
print(s['메로나'])
print(s[0])

1000
1000


In [16]:
s1 = Series([10,20,30])
s2 = Series([10,20,30], index=[1,2,3])
print(s1[0])
print(s2[1])

10
10


In [17]:
s3 = Series([10, 20, 30], index=['a', 'b', 'c'])

In [18]:
print(s3)

a    10
b    20
c    30
dtype: int64


In [19]:
print(s3[0])

10


In [20]:
print(s3.index[0])

a


In [21]:
print(s3.index[-1])

c


In [22]:
from pandas import Series

data = [100,200,300]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data = data, index=index)
print(s.iloc[0:2])

메로나    100
구구콘    200
dtype: int64


In [23]:
print(s.loc['메로나': '구구콘'])

메로나    100
구구콘    200
dtype: int64


In [24]:
indice = [0,2]
print(s.iloc[ indice ])
print(s.iloc[ [0,2]])

메로나     100
하겐다즈    300
dtype: int64
메로나     100
하겐다즈    300
dtype: int64


In [25]:
indice = ["메로나", "하겐다즈"]
print(s.loc[ indice ])
print(s.loc[["메로나", "하겐다즈"]])

메로나     100
하겐다즈    300
dtype: int64
메로나     100
하겐다즈    300
dtype: int64


In [5]:
from pandas import Series

data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)

s.loc['메로나'] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
dtype: int64


In [6]:
s.iloc[0] = 500
s['메로나'] = 500

In [7]:
s.loc['비비빅'] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [8]:
print(s.drop('메로나'))
print(s.drop(0))

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


KeyError: '[0] not found in axis'

In [10]:
s = s.drop('메로나')
print(s)

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [11]:
철수 = Series([10,20,30], index=['naver','skt','kt'])
영희 = Series([10,20,30], index=['skt', 'kt', 'naver'])
가족 = 철수 + 영희
print(가족)

kt       50
naver    40
skt      30
dtype: int64


In [12]:
print(철수*10)

naver    100
skt      200
kt       300
dtype: int64


In [13]:
high = Series([42800, 42700, 42050, 42950, 43000])
low = Series([42150, 42150, 41300, 42150, 42350])

diff = high - low
print(diff)

0    650
1    550
2    750
3    800
4    650
dtype: int64


In [14]:
print(diff.max())

800


In [18]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = Series([42800, 42700, 42050, 42950, 43000], index=date)
low = Series([42150, 42150, 41300, 42150, 42350], index = date)
diff = high-low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [19]:
max_idx = 0
max_val = 0

for i in range(len(diff)):
    if diff[i] >max_val:
        max_val = diff[i]
        max_idx = i

print(max_idx)
print(diff.index[max_idx])

3
6/4


In [20]:
print(diff.idxmax())
print(diff.idxmin())

6/4
6/2


In [21]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = Series([42800, 42700, 42050, 42950, 43000], index=date)
low = Series([42150, 42150, 41300, 42150, 42350], index = date)
profit = high/low
print(profit)

6/1    1.015421
6/2    1.013049
6/3    1.018160
6/4    1.018980
6/5    1.015348
dtype: float64


In [22]:
print(profit.cumprod())

6/1    1.015421
6/2    1.028671
6/3    1.047351
6/4    1.067230
6/5    1.083610
dtype: float64


In [23]:
print(profit.cumprod().iloc[-1])

1.0836101509172456


In [24]:
data = {
    "삼성전자" : "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)

In [25]:
print(s.unique())

['전기,전자' '운수장비' '서비스업']


In [27]:
s.value_counts()

전기,전자    2
서비스업     2
운수장비     1
dtype: int64

In [28]:
from pandas import Series
s = Series(["1,234", "5,678", "9,876"])
print( int(s) )

TypeError: cannot convert the series to <class 'int'>

In [29]:
def remove_comma(x) :
    print(x, 'in function')
    return x

s = Series(["1,234", "5,678", "9,876"])
result = s.map(remove_comma)
print(result)

1,234 in function
5,678 in function
9,876 in function
0    1,234
1    5,678
2    9,876
dtype: object


In [30]:
from pandas import Series

def remove_comma(x) :
    return int(x.replace(",", ""))

s = Series(["1,234", "5,678", "9,876"])
result = s.map(remove_comma)
print(result)

0    1234
1    5678
2    9876
dtype: int64


In [32]:
def is_greater_than_5000(x):
    if x> 5000:
        return "크다"
    else:
        return "작다"
    
s = Series([1234, 5678, 9876])
s = s.map(is_greater_than_5000)
print(s)

0    작다
1    크다
2    크다
dtype: object


In [33]:
from pandas import Series

data = [42500, 42440, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28','2019-05-27']
s = Series(data=data, index=index)
cond = s >42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [34]:
print(s[cond])

2019-05-31    42500
2019-05-30    42440
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [36]:
close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
open = Series(data = open, index=index)
close = Series(data=close, index=index)

cond = close>open
print(cond)

2019-05-31    False
2019-05-30     True
2019-05-29    False
2019-05-28    False
2019-05-27     True
dtype: bool


In [37]:
cond = close >open
print(close[cond])

2019-05-30    42550
2019-05-27    42650
dtype: int64


In [38]:
print(close[close>open])

2019-05-30    42550
2019-05-27    42650
dtype: int64


In [39]:
print(close.index[close>open])
print(close[close>open].index)

Index(['2019-05-30', '2019-05-27'], dtype='object')
Index(['2019-05-30', '2019-05-27'], dtype='object')


In [40]:
close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29','2019-05-28', '2019-05-27']

open = Series(data=open, index=index)
close = Series(data= close, index=index)
diff = close - open
print(diff[close > open])

2019-05-30    350
2019-05-27    150
dtype: int64


In [41]:
data = [3.1, 2.0, 10.1, 5.1]
index = ['000010', '000020', '000030', '000040']
s = Series(data = data, index=index)

In [42]:
print(s)
s1= s.sort_values()
print(s1)

s2 = s.sort_values(ascending=False)
print(s2)

000010     3.1
000020     2.0
000030    10.1
000040     5.1
dtype: float64
000020     2.0
000010     3.1
000040     5.1
000030    10.1
dtype: float64
000030    10.1
000040     5.1
000010     3.1
000020     2.0
dtype: float64


In [43]:
data = [3.1, 2.0, 10.1, 3.1]
index = ['000010', '000020', '000030', '000040']
s = Series(data=data, index=index)
print(s.rank())

000010    2.5
000020    1.0
000030    4.0
000040    2.5
dtype: float64


In [44]:
print(s.rank(ascending = False))

000010    2.5
000020    4.0
000030    1.0
000040    2.5
dtype: float64


In [5]:
from pandas import DataFrame

data = {
    '종목코드':['037730', '036360', '005760'],
    '종목명': ['3R', '3S0FT', 'ACTS'],
    '현재가': [1510, 1790, 1185]
    
}
df = DataFrame(data)
print(df)

     종목코드    종목명   현재가
0  037730     3R  1510
1  036360  3S0FT  1790
2  005760   ACTS  1185


In [5]:
from pandas import DataFrame

data = [
    ['037730', '036360', '005760'],
    ['3R', '3S0FT', 'ACTS'],
    [1510, 1790, 1185]
    
]
columns = ['종목코드', '종목명', '현재가']
df = DataFrame(data= data, columns=columns)
print(df)

     종목코드     종목명     현재가
0  037730  036360  005760
1      3R   3S0FT    ACTS
2    1510    1790    1185


In [8]:
from pandas import DataFrame

data = [
    {'종목코드': '037730', '종목명': '3R', '현재가':1510},
    {'종목코드': '036360', '종목명': '3S0FT', '현재가':1790},
    {'종목코드': '005760', '종목명': 'ACTS', '현재가':1185}
    
    
]

df = DataFrame(data=data)
print(df)

     종목코드    종목명   현재가
0  037730     3R  1510
1  036360  3S0FT  1790
2  005760   ACTS  1185


In [10]:
data = [
    ['037730','3R', 1510, 7.36],
    ['036360', '3S0FT', 1790, 1.65],
    ['005670', 'ACTS', 1185, 1.28]
    
]

columns = ['종목코드', '종목명', '현재가', '등락률']
df = DataFrame(data=data, columns=columns)
df = df.set_index('종목코드')
print(df)

          종목명   현재가   등락률
종목코드                     
037730     3R  1510  7.36
036360  3S0FT  1790  1.65
005670   ACTS  1185  1.28


In [12]:
data = [
    ['037730','3R', 1510, 7.36],
    ['036360', '3S0FT', 1790, 1.65],
    ['005670', 'ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목코드', '종목명', '현재가', '등락률']

df = DataFrame(data=data, index=index, columns=columns)
df = df.set_index('종목코드')
print(df)

          종목명   현재가   등락률
종목코드                     
037730     3R  1510  7.36
036360  3S0FT  1790  1.65
005670   ACTS  1185  1.28


In [13]:
data = [
    ['037730','3R', 1510, 7.36],
    ['036360', '3S0FT', 1790, 1.65],
    ['005670', 'ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목코드', '종목명', '현재가', '등락률']

df = DataFrame(data=data, index=index, columns=columns)
df = df.set_index('종목코드')
print(df['현재가'])

종목코드
037730    1510
036360    1790
005670    1185
Name: 현재가, dtype: int64


In [14]:
print(df.현재가)

종목코드
037730    1510
036360    1790
005670    1185
Name: 현재가, dtype: int64


In [15]:
리스트 = ['현재가', '등락률']
df[리스트]

현재가   등락률
종목코드              
037730  1510  7.36
036360  1790  1.65
005670  1185  1.28

In [16]:
print(df[['현재가', '등락률']])

         현재가   등락률
종목코드              
037730  1510  7.36
036360  1790  1.65
005670  1185  1.28


In [17]:
df[['현재가', '등락률']]

현재가   등락률
종목코드              
037730  1510  7.36
036360  1790  1.65
005670  1185  1.28

In [18]:
data = [
    ['037730','3R', 1510, 7.36],
    ['036360', '3S0FT', 1790, 1.65],
    ['005670', 'ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목코드', '종목명', '현재가', '등락률']

df = DataFrame(data=data, index=index, columns=columns)
print(df.loc['037730'])

종목코드    037730
종목명         3R
현재가       1510
등락률       7.36
Name: 037730, dtype: object


In [19]:
print(df.iloc[0])
print(df.iloc[-1])

종목코드    037730
종목명         3R
현재가       1510
등락률       7.36
Name: 037730, dtype: object
종목코드    005670
종목명       ACTS
현재가       1185
등락률       1.28
Name: 005760, dtype: object


In [20]:
print(df.loc[['037730', '036360']])
print(df.iloc[[0,1]])

          종목코드    종목명   현재가   등락률
037730  037730     3R  1510  7.36
036360  036360  3S0FT  1790  1.65
          종목코드    종목명   현재가   등락률
037730  037730     3R  1510  7.36
036360  036360  3S0FT  1790  1.65


In [23]:
data = [
    ['3R', 1510, 7.36],
    [ '3S0FT', 1790, 1.65],
    [ 'ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목명', '현재가', '등락률']

df = DataFrame(data=data, index=index, columns=columns)

print(df.iloc[0])
print(df.loc['037730'])

종목명      3R
현재가    1510
등락률    7.36
Name: 037730, dtype: object
종목명      3R
현재가    1510
등락률    7.36
Name: 037730, dtype: object


In [26]:
print(df.iloc[0].iloc[1])
print(df.iloc[0].loc['현재가'])
print(df.iloc[0]['현재가'])

1510
1510
1510


In [27]:
data = [
    ['3R', 1510, 7.36],
    [ '3S0FT', 1790, 1.65],
    [ 'ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목명', '현재가', '등락률']

df = DataFrame(data=data, index=index, columns=columns)

print(df.loc[['037730', '036360']])
print(df.iloc[[0,1]])

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3S0FT  1790  1.65
          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3S0FT  1790  1.65


In [28]:
df = df.loc[['037730', '036360']]
df = df[['종목명', '현재가']]
df

종목명   현재가
037730     3R  1510
036360  3S0FT  1790

In [29]:
df.loc[['037730', '036360'], ['종목명', '현재가']]
df.iloc[[0,1], [0,1]]

종목명   현재가
037730     3R  1510
036360  3S0FT  1790

In [6]:
data = [
    ['3R', 1510, 7.36],
    ['3S0FT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목명', '현재가', '등락률']
df = DataFrame(data= data, index=index, columns= columns)
cond = df['현재가'] >= 1400
print(df.loc[cond])

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3S0FT  1790  1.65


In [7]:
cond = df['현재가'] >=1400
print(df.loc[cond]['현재가'])
print(df.loc[cond , '현재가'])

037730    1510
036360    1790
Name: 현재가, dtype: int64
037730    1510
036360    1790
Name: 현재가, dtype: int64


In [8]:
cond = (df['현재가']>=1400) & (df['현재가']<1700)
print(df.loc[cond])

       종목명   현재가   등락률
037730  3R  1510  7.36


In [10]:
cond = df['현재가'] >= (1400&df['현재가'])<1700
print(df.loc[cond])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [11]:
cond = (df['현재가'] >= 1400) & (df['현재가']<1700)
print(df.loc[~cond])

          종목명   현재가   등락률
036360  3S0FT  1790  1.65
005760   ACTS  1185  1.28


In [12]:
data = [
    ['3R', 1510, 7.36],
    ['3S0FT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목명', '현재가', '등락률']
df = DataFrame(data= data, index=index, columns= columns)

In [6]:
from pandas import Series
s = Series(data=[1600,1600,1600], index=df.index)
df['목표가'] = s
print(df)

NameError: name 'df' is not defined

In [16]:
df['목표가'] = 1600
print(df)

          종목명   현재가   등락률   목표가
037730     3R  1510  7.36  1600
036360  3S0FT  1790  1.65  1600
005760   ACTS  1185  1.28  1600


In [17]:
df["괴리율"] = (df['목표가']-df['현재가'])/df['현재가']
print(df)

          종목명   현재가   등락률   목표가       괴리율
037730     3R  1510  7.36  1600  0.059603
036360  3S0FT  1790  1.65  1600 -0.106145
005760   ACTS  1185  1.28  1600  0.350211


In [18]:
data = [
    ['3R', 1510, 7.36],
    ['3S0FT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목명', '현재가', '등락률']
df = DataFrame(data= data, index=index, columns= columns)

In [20]:
s = Series(data=['LG 전자', 6000, 3.84],index=df.columns)
df.loc['066570'] = s
df

종목명   현재가   등락률
037730     3R  1510  7.36
036360  3S0FT  1790  1.65
005760   ACTS  1185  1.28
066570  LG 전자  6000  3.84

In [21]:
df.loc['066570'] = ['LG 전자', 60000, 3.84]
df

종목명    현재가   등락률
037730     3R   1510  7.36
036360  3S0FT   1790  1.65
005760   ACTS   1185  1.28
066570  LG 전자  60000  3.84

In [22]:
s = Series(data=['LG전자', 60000, 3.84], index=df.columns, name='066570')
new_df = df.append(s)
print(new_df)

          종목명    현재가   등락률
037730     3R   1510  7.36
036360  3S0FT   1790  1.65
005760   ACTS   1185  1.28
066570  LG 전자  60000  3.84
066570   LG전자  60000  3.84


In [23]:
data = [
    ['3R', 1510, 7.36],
    ['3S0FT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
    
]

index = ['037730', '036360', '005760']
columns = ['종목명', '현재가', '등락률']
df = DataFrame(data= data, index=index, columns= columns)

df_new = df.drop('현재가', axis=1)
print(df)
print(df_new)

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3S0FT  1790  1.65
005760   ACTS  1185  1.28
          종목명   등락률
037730     3R  7.36
036360  3S0FT  1.65
005760   ACTS  1.28


In [24]:
df_new = df.drop('037730', axis= 0)
print(df)
print(df_new)

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3S0FT  1790  1.65
005760   ACTS  1185  1.28
          종목명   현재가   등락률
036360  3S0FT  1790  1.65
005760   ACTS  1185  1.28


In [27]:
df.drop('037730', axis = 0, inplace=True)
print(df)

KeyError: "['037730'] not found in axis"

KeyError: "['037730'] not found in axis"

In [28]:
data = [
    ['3R',1510, 7.36],
    ['3S0FT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
    
]

index = ['037730', '036360','005760']
columns = ['종목명', '현재가', '등락률']
df = DataFrame(data=data, index=index, columns=columns)
print(df.columns)
print(df.index)

Index(['종목명', '현재가', '등락률'], dtype='object')
Index(['037730', '036360', '005760'], dtype='object')


In [29]:
df.columns = ['name', 'close', 'fluctuation']
df.index.name = 'code'
print(df)

         name  close  fluctuation
code                             
037730     3R   1510         7.36
036360  3S0FT   1790         1.65
005760   ACTS   1185         1.28


In [30]:
data = [
    ['3R',1510, 7.36],
    ['3S0FT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
    
]

index = ['037730', '036360','005760']
columns = ['종목명', '현재가', '등락률']
df = DataFrame(data=data, index=index, columns=columns)
df.rename(columns={'종목명':'code'}, inplace=True)
print(df)

         code   현재가   등락률
037730     3R  1510  7.36
036360  3S0FT  1790  1.65
005760   ACTS  1185  1.28


In [35]:
data = [
    ['1,000', '1,100', '1,510'],
    ['1,410', '1,420', '1,790'],
    ['850', '900', '1,185']
    
]
columns = ['03/02', '03/03', '03/04']
df = DataFrame(data=data, columns=columns)
df

03/02  03/03  03/04
0  1,000  1,100  1,510
1  1,410  1,420  1,790
2    850    900  1,185

In [33]:
def remove_comma(x):
    return int(x.replace(',',''))
                         
df['03/02'] = df['03/02'].map(remove_comma)
df['03/03'] = df['03/03'].map(remove_comma)
df['03/04'] = df['03/04'].map(remove_comma)
print(df)

   03/02  03/03  03/04
0   1000   1100   1510
1   1410   1420   1790
2    850    900   1185


In [36]:
def remove_comma(x):
    return int(x.replace(',',''))

df = df.applymap(remove_comma)
print(df)
print(df.dtypes)

   03/02  03/03  03/04
0   1000   1100   1510
1   1410   1420   1790
2    850    900   1185
03/02    int64
03/03    int64
03/04    int64
dtype: object


In [38]:
import numpy as np
from pandas import DataFrame

def remove_comma(x):
    return x.replace(",", "")

data = [
    ['1,000', '1,100', '1,510'],
    ['1,410', '1,420', '1,790'],
    ['850', '900', '1,185'],
    
]

columns = ['03/02', '03/03', '03/04']
df = DataFrame(data=data, columns=columns)
df = df.applymap(remove_comma)
df = df.astype({'03/02':np.int64, '03/03':np.int64, '03/04':np.int64})
print(df.dtypes)

03/02    int64
03/03    int64
03/04    int64
dtype: object


In [39]:
from pandas import DataFrame
import numpy as np

data = [
    {'cd':'A060310', 'nm':'3S', 'close':'2,920'},
    {'cd':'A095570', 'nm':'AJ네트웍스', 'close':'6,250'},
    {'cd':'A006840', 'nm':'AK홀딩스', 'close':'29,700'},
    {'cd':'A054620', 'nm':'APS홀딩스', 'close':'19,400'}
    
]
df = DataFrame(data=data)
df

cd      nm   close
0  A060310      3S   2,920
1  A095570  AJ네트웍스   6,250
2  A006840   AK홀딩스  29,700
3  A054620  APS홀딩스  19,400

In [40]:
df['cd'] = df['cd'].str[1:]

In [41]:
df['close'] =df['close'].str.replace(',','').astype(np.int64)

In [45]:
from pandas import DataFrame

data = [
    {'cd':'A060310', 'nm':'3S', 'open':2920,'close':'2,920'},
    {'cd':'A095570', 'nm':'AJ네트웍스','open':1920, 'close':'6,250'},
    {'cd':'A006840', 'nm':'AK홀딩스','open':2020, 'close':'29,700'},
    {'cd':'A054620', 'nm':'APS홀딩스','open':3120, 'close':'19,400'}
    
]
df = DataFrame(data=data)
df = df.set_index('cd')
df

nm  open   close
cd                           
A060310      3S  2920   2,920
A095570  AJ네트웍스  1920   6,250
A006840   AK홀딩스  2020  29,700
A054620  APS홀딩스  3120  19,400

In [46]:
cond = df['open'] >= 2000
print(df[cond])

             nm  open   close
cd                           
A060310      3S  2920   2,920
A006840   AK홀딩스  2020  29,700
A054620  APS홀딩스  3120  19,400


In [48]:
print(df.query("nm=='3S'"))
print(df.query('nm=="3s"'))

         nm  open  close
cd                      
A060310  3S  2920  2,920
Empty DataFrame
Columns: [nm, open, close]
Index: []


In [51]:
print(df.query("open>close"))

TypeError: '>' not supported between instances of 'int' and 'str'

In [52]:
print(df.query("nm in ['3S', 'AK홀딩스']"))

            nm  open   close
cd                          
A060310     3S  2920   2,920
A006840  AK홀딩스  2020  29,700


In [54]:
df.query("cd == 'A060310'")

nm  open  close
cd                      
A060310  3S  2920  2,920

In [55]:
name = "AJ네트웍스"
df.query('nm == @name')

nm  open  close
cd                          
A095570  AJ네트웍스  1920  6,250

In [57]:
from pandas import DataFrame

data = [
    [1416, 1416, 2994, 1755],
    [6.42, 17.63, 21.09, 13.93],
    [1.10, 1.49, 2.06, 1.88]
]

columns = ['2018/12', '2019/12', '2020/12', '2021/12(E)' ]
index = ['DPS', 'PER', "PBR"]

df = DataFrame(data= data, index=index, columns=columns)
print(df)

     2018/12  2019/12  2020/12  2021/12(E)
DPS  1416.00  1416.00  2994.00     1755.00
PER     6.42    17.63    21.09       13.93
PBR     1.10     1.49     2.06        1.88


In [58]:
df.filter(items=['2018/12'])

2018/12
DPS  1416.00
PER     6.42
PBR     1.10

In [59]:
df.filter(items=["PER"], axis=0)

2018/12  2019/12  2020/12  2021/12(E)
PER     6.42    17.63    21.09       13.93

In [60]:
df.filter(regex='2020')

2020/12
DPS  2994.00
PER    21.09
PBR     2.06

In [61]:
df.filter(regex="^2020")

2020/12
DPS  2994.00
PER    21.09
PBR     2.06

In [62]:
df.filter(regex="R$", axis=0)

2018/12  2019/12  2020/12  2021/12(E)
PER     6.42    17.63    21.09       13.93
PBR     1.10     1.49     2.06        1.88

In [63]:
df.filter(regex="\d{4}")

2018/12  2019/12  2020/12  2021/12(E)
DPS  1416.00  1416.00  2994.00     1755.00
PER     6.42    17.63    21.09       13.93
PBR     1.10     1.49     2.06        1.88

In [65]:
df.filter(regex="\d{4}/\d{2}$")

2018/12  2019/12  2020/12
DPS  1416.00  1416.00  2994.00
PER     6.42    17.63    21.09
PBR     1.10     1.49     2.06

In [16]:
from pandas import DataFrame
data = [
    ['037730', '3R', 1510],
    ['036360', '3S0FT', 1790],
    ['005670', 'ACTS', 1185]
]

columns = ['종목코드', '종목명', '현재가']
df = DataFrame(data = data, columns=columns)
df.set_index('종목코드', inplace=True)

In [17]:
df2 = df.sort_values('현재가')
print(df2)

          종목명   현재가
종목코드               
005670   ACTS  1185
037730     3R  1510
036360  3S0FT  1790


In [18]:
df2 = df.sort_values(by="현재가")
print(df2)

          종목명   현재가
종목코드               
005670   ACTS  1185
037730     3R  1510
036360  3S0FT  1790


In [19]:
df2 = df.sort_values(by='현재가', ascending=False)
print(df2)

          종목명   현재가
종목코드               
036360  3S0FT  1790
037730     3R  1510
005670   ACTS  1185


In [20]:
df['순위'] = df['현재가'].rank()
print(df)

          종목명   현재가   순위
종목코드                    
037730     3R  1510  2.0
036360  3S0FT  1790  3.0
005670   ACTS  1185  1.0


In [21]:
df.sort_values(by='순위', inplace=True)
print(df)

          종목명   현재가   순위
종목코드                    
005670   ACTS  1185  1.0
037730     3R  1510  2.0
036360  3S0FT  1790  3.0


In [22]:
import pandas as pd

idx1 =pd.Index([1,2,3])
idx2 =pd.Index([2,3,4])
print(type(idx1))

<class 'pandas.core.indexes.numeric.Int64Index'>


In [23]:
idx1.union(idx2)

Int64Index([1, 2, 3, 4], dtype='int64')

In [24]:
idx1.intersection(idx2)

Int64Index([2, 3], dtype='int64')

In [26]:
idx1.difference(idx2)

Int64Index([1], dtype='int64')

In [28]:
from pandas import DataFrame

data =[
    ['2차전지(생산)', 'SK이노베이션', 10.19, 1.29],
    ['해운','팬오션', 21.33, 0.95],
    ['시스템반도체', '티엘아이', 35.97, 1.12],
    ['해운','HMM',21.52,3.20],
    ['시스템반도체', '아이에이', 37.32, 3.55],
    ['2차전지(생산)', 'LG화학',83.06,3.75]
]

columns = ['테마', '종목명', 'PER', 'PBR']
df = DataFrame(data=data, columns=columns)
df1 = df[df['테마'] == '2차전지(생산)']

In [30]:
df

테마      종목명    PER   PBR
0  2차전지(생산)  SK이노베이션  10.19  1.29
1        해운      팬오션  21.33  0.95
2    시스템반도체     티엘아이  35.97  1.12
3        해운      HMM  21.52  3.20
4    시스템반도체     아이에이  37.32  3.55
5  2차전지(생산)     LG화학  83.06  3.75

In [31]:
df1

테마      종목명    PER   PBR
0  2차전지(생산)  SK이노베이션  10.19  1.29
5  2차전지(생산)     LG화학  83.06  3.75

In [32]:
df2 = df[df['테마'] == '해운']
df3 = df[df['테마'] == '시스템반도체']

In [33]:
mean1 = df1['PER'].mean()
mean2 = df2["PER"].mean()
mean3 = df3["PER"].mean()

In [34]:
print(mean1)
print(mean2)
print(mean3)

46.625
21.424999999999997
36.644999999999996


In [35]:
data = [mean1, mean2, mean3]
index = ['2차전지(생산)', '해운', '시스템반도체']
s =pd.Series(data==data, index=index)

In [36]:
s

2차전지(생산)    True
해운          True
시스템반도체      True
dtype: bool

In [37]:
df.groupby('테마')['PER'].mean()

테마
2차전지(생산)    46.625
시스템반도체      36.645
해운          21.425
Name: PER, dtype: float64

In [38]:
gb =df.groupby('테마')
temp = gb.get_group('2차전지(생산)')
print(temp)

         테마      종목명    PER   PBR
0  2차전지(생산)  SK이노베이션  10.19  1.29
5  2차전지(생산)     LG화학  83.06  3.75


In [39]:
temp = df[['테마', 'PER', 'PBR']].groupby('테마').get_group('2차전지(생산)')
print(temp)

         테마    PER   PBR
0  2차전지(생산)  10.19  1.29
5  2차전지(생산)  83.06  3.75


In [40]:
temp = df.groupby('테마')[['PER', 'PBR']].get_group('2차전지(생산)')
print(temp)

     PER   PBR
0  10.19  1.29
5  83.06  3.75


In [41]:
df.groupby('테마')[['PER', 'PBR']].mean()

PER    PBR
테마                     
2차전지(생산)  46.625  2.520
시스템반도체    36.645  2.335
해운        21.425  2.075

In [42]:
df.groupby('테마').mean()

PER    PBR
테마                     
2차전지(생산)  46.625  2.520
시스템반도체    36.645  2.335
해운        21.425  2.075

In [43]:
df.groupby("테마").agg({'PER':max, "PBR":min})

PER   PBR
테마                   
2차전지(생산)  83.06  1.29
시스템반도체    37.32  1.12
해운        21.52  0.95

In [44]:
import numpy as np
df.groupby('테마').agg({'PER':[min, max], 'PBR':[ np.std, np.var]})

PER              PBR         
            min    max       std      var
테마                                       
2차전지(생산)  10.19  83.06  1.739483  3.02580
시스템반도체    35.97  37.32  1.718269  2.95245
해운        21.33  21.52  1.590990  2.53125

In [45]:
from pandas import DataFrame

import pandas as pd

data ={
    '종가': [113000, 111500],
    '거래량': [555850, 282163]
}

index = ['2019-06-21', '2019-06-20']
df1 = DataFrame(data=data, index=index)

data = {
    '시가': [112500, 110000],
    '고가': [115000, 112000],
    '저가': [111500, 109000]
    
}

index = ['2019-06-21', '2019-06-20']
df2 = DataFrame(data=data, index=index)

df = pd.concat([df1, df2], axis=1)
print(df)

                종가     거래량      시가      고가      저가
2019-06-21  113000  555850  112500  115000  111500
2019-06-20  111500  282163  110000  112000  109000


In [46]:
정렬순서 = ['시가', '고가', '저가', '종가', '거래량']
df = df[정렬순서]
print(df)

                시가      고가      저가      종가     거래량
2019-06-21  112500  115000  111500  113000  555850
2019-06-20  110000  112000  109000  111500  282163


In [47]:
data = {
    '종가':[113000, 111500],
    '거래량': [555850, 282163]
    
}

index = ['2019-06-21', '2019-06-20']
df1 = DataFrame(data=data, index=index)

data = {
    '시가' : [112500,110000],
    '고가' : [115000, 112000],
    '저가' : [111500, 109000]
    
}

index = ['2019-06-20', '2019-06-19']
df2 =DataFrame(data=data, index=index)

df= pd.concat([df1,df2], axis=1)
print(df)


                  종가       거래량        시가        고가        저가
2019-06-21  113000.0  555850.0       NaN       NaN       NaN
2019-06-20  111500.0  282163.0  112500.0  115000.0  111500.0
2019-06-19       NaN       NaN  110000.0  112000.0  109000.0


In [48]:
df = pd.concat([df1, df2], axis=1, join='inner')
print(df)

                종가     거래량      시가      고가      저가
2019-06-20  111500  282163  112500  115000  111500


In [49]:
data = {
    '종가':[113000, 111500],
    '거래량': [555850, 282163]
    
}

index = ['2019-06-21', '2019-06-20']
df1 =DataFrame(data, index=index)


data = {
    '종가':[110000, 483689],
    '거래량': [109000, 791946]
    
}

index = ['2019-06-19', '2019-06-18']
df2 = DataFrame(data, index=index)

df = df1.append(df2)
print(df)

                종가     거래량
2019-06-21  113000  555850
2019-06-20  111500  282163
2019-06-19  110000  109000
2019-06-18  483689  791946


In [50]:
df = pd.concat([df1,df2])
print(df)

                종가     거래량
2019-06-21  113000  555850
2019-06-20  111500  282163
2019-06-19  110000  109000
2019-06-18  483689  791946


In [11]:
from pandas import DataFrame
import pandas as pd

data = [
    ['전기전가', '005930', '삼성전자', 74400],
    ['화학','051910', "LG화학", 896000],
    ['전기전자', '000660', "SK하이닉스", 101500]
]

columns = ['업종', '종목코드', '종목명', '현재가']
df1 = DataFrame(data=data, columns=columns)

data = [
    
    ['은행', 2.92],
    ['보험', 0.37],
    ['화학',0.06],
    ['전기전가', -2.43]
]

columns = ['업종', '등락률']
df2 = DataFrame(data=data, columns=columns)

In [12]:
df = pd.merge(left=df1, right=df2, on='업종')
print(df)

     업종    종목코드   종목명     현재가   등락률
0  전기전가  005930  삼성전자   74400 -2.43
1    화학  051910  LG화학  896000  0.06


In [13]:
data = [
    ['전기전가', '005930', '삼성전자', 74400],
    ['화학','051910', "LG화학", 896000],
    ['서비스업', '000660', "카카오", 101500]
]

columns = ['업종', '종목코드', '종목명', '현재가']
df1 = DataFrame(data=data, columns=columns)

data = [
    
    ['은행', 2.92],
    ['보험', 0.37],
    ['화학',0.06],
    ['전기전가', -2.43]
]

columns = ['업종', '등락률']
df2 = DataFrame(data=data, columns=columns)

In [14]:
df = pd.merge(left=df1, right=df2, how='left',on='업종')
print(df)

     업종    종목코드   종목명     현재가   등락률
0  전기전가  005930  삼성전자   74400 -2.43
1    화학  051910  LG화학  896000  0.06
2  서비스업  000660   카카오  101500   NaN


In [15]:
data = [
    ['전기전가', '005930', '삼성전자', 74400],
    ['화학','051910', "LG화학", 896000],
    ['서비스업', '000660', "카카오", 101500]
]

columns = ['업종', '종목코드', '종목명', '현재가']
df1 = DataFrame(data=data, columns=columns)

data = [
    
    ['은행', 2.92],
    ['보험', 0.37],
    ['화학',0.06],
    ['전기전가', -2.43]
]

columns = ['항목', '등락률']
df2 = DataFrame(data=data, columns=columns)

In [16]:
df = pd.merge(left=df1, right=df2, left_on='업종', right_on='항목')
print(df)

     업종    종목코드   종목명     현재가    항목   등락률
0  전기전가  005930  삼성전자   74400  전기전가 -2.43
1    화학  051910  LG화학  896000    화학  0.06


In [17]:
from pandas import DataFrame
import pandas as pd

data = [
    ['전기전자','005930', '삼성전자',74400],
    ['화학', '051910', '화학', 896000],
    ['서비스업', '035720','카카오', 121500]
]

columns = ['업종', '종목코드','종목명','현재가']

df1 = DataFrame(data=data, columns=columns)
df = df1.set_index('업종')

data = [
    ['은행',2.92],
    ['보험', 0.37],
    ['화학',0.06],
    ['전기전자',-2.43]
]

columns = ['항목','등락률']
df2 = DataFrame(data=data, columns=columns)
df2 = df2.set_index('항목')

In [18]:
df1.join(other=df2)

업종    종목코드   종목명     현재가  등락률
0  전기전자  005930  삼성전자   74400  NaN
1    화학  051910    화학  896000  NaN
2  서비스업  035720   카카오  121500  NaN

In [19]:
data = [
    
    ['2017','삼성',500],
    ['2017','lg',300],
    ['2017','sk하이닉스',200],
    ['2018','삼성',600],
    ['2018','lg',400],
    ['2018','sk하이닉스',300],
]

columns = ['연도', '회사', '시가총액']
df = DataFrame(data=data, columns=columns)
print(df)

     연도      회사  시가총액
0  2017      삼성   500
1  2017      lg   300
2  2017  sk하이닉스   200
3  2018      삼성   600
4  2018      lg   400
5  2018  sk하이닉스   300


In [20]:
df_mean = df.groupby('연도')['시가총액'].mean().to_frame()
df_mean.columns = ['시가총액평균']
print(df_mean)

          시가총액평균
연도              
2017  333.333333
2018  433.333333


In [21]:
df = df.join(df_mean, on='연도')

In [22]:
import numpy as np

df['규모'] = np.where(df['시가총액'] >=df['시가총액평균'], '대형주', '중/소형주')
df

연도      회사  시가총액      시가총액평균     규모
0  2017      삼성   500  333.333333    대형주
1  2017      lg   300  333.333333  중/소형주
2  2017  sk하이닉스   200  333.333333  중/소형주
3  2018      삼성   600  433.333333    대형주
4  2018      lg   400  433.333333  중/소형주
5  2018  sk하이닉스   300  433.333333  중/소형주

In [23]:
from pandas import DataFrame
import pandas as pd

data = [
    ['영업이익', '컨센서스', 1000, 1200],
    ['영업이익', '잠정치', 900, 1400],
    ['당기순이익', '컨센서스', 800, 900],
    ['당기순이익', '장정치', 700, 800],
    
]

df = DataFrame(data=data)
df = df.set_index([0,1])
df

2     3
0     1               
영업이익  컨센서스  1000  1200
      잠정치    900  1400
당기순이익 컨센서스   800   900
      장정치    700   800

In [24]:
df.index.names = ['재무연월', ""]
df.columns = ['2020/06', '2020/09']
df

2020/06  2020/09
재무연월                        
영업이익  컨센서스     1000     1200
      잠정치       900     1400
당기순이익 컨센서스      800      900
      장정치       700      800

In [25]:
print(df.loc['영업이익'])

      2020/06  2020/09
                      
컨센서스     1000     1200
잠정치       900     1400


In [28]:
print(df.loc[('영업이익', '컨센서스')])

2020/06    1000
2020/09    1200
Name: (영업이익, 컨센서스), dtype: int64


In [29]:
print(df.iloc[0])

2020/06    1000
2020/09    1200
Name: (영업이익, 컨센서스), dtype: int64


In [30]:
print(df.iloc[0,0])

1000


In [31]:
df.loc[('영업이익', '컨센서스'), '2020/06']

1000

In [32]:
a = [1,2,3,4,5]
print(a[0:5:2])
print(a[slice(0,5,2)])

[1, 3, 5]
[1, 3, 5]


In [33]:
a = [1,2,3,4,5]
b= [3,4,5,6,7]

s = slice(0,5,2)
print(a[s])
print(b[s])

[1, 3, 5]
[3, 5, 7]


In [34]:
a = [1,2,3,4,5]

print(a[:])
print(a[slice(None)])
print(a[ : :])
print(a[slice(None, None)])

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [36]:
print(df.loc[( :, '컨센서스'),  : ])

SyntaxError: invalid syntax (Temp/ipykernel_26900/4272317044.py, line 1)

In [37]:
print(df.loc[(slice(None), '컨센서스'), :])

            2020/06  2020/09
재무연월                        
영업이익  컨센서스     1000     1200
당기순이익 컨센서스      800      900


In [39]:
idx = pd.IndexSlice
print(df.loc[ idx[ : , '컨센서스'], :])

            2020/06  2020/09
재무연월                        
영업이익  컨센서스     1000     1200
당기순이익 컨센서스      800      900


In [40]:
from pandas import DataFrame

data = [
    [1000, 900, 800, 700],
    [1200, 1400, 900, 800]
]

columns = [
    ['영업이익', '영업이익', '당기순이익', '당기순이익'],
    ['컨센서스', '잠정치', '컨센서스', '잠정치']
]

df = DataFrame(data=data, index=['2020/06', '2020/09'], columns=columns)
df

영업이익       당기순이익     
         컨센서스   잠정치  컨센서스  잠정치
2020/06  1000   900   800  700
2020/09  1200  1400   900  800

In [41]:
import pandas as pd

level_0 = ['영업이익', '당기순이익']
level_1 = ['컨센서스', '잠정치']

idx = pd.MultiIndex.from_product([level_0, level_1])

print(idx)
print(idx.get_level_values(0))

MultiIndex([( '영업이익', '컨센서스'),
            ( '영업이익',  '잠정치'),
            ('당기순이익', '컨센서스'),
            ('당기순이익',  '잠정치')],
           )
Index(['영업이익', '영업이익', '당기순이익', '당기순이익'], dtype='object')


In [42]:
level_0 = ['영업이익', '당기순이익']
level_1 = ['컨센서스', '잠정치']
columns = pd.MultiIndex.from_product([level_0, level_1])
df = DataFrame(data=data, index=['2020/06', '2020/09'], columns=columns)
df

영업이익       당기순이익     
         컨센서스   잠정치  컨센서스  잠정치
2020/06  1000   900   800  700
2020/09  1200  1400   900  800

In [43]:
df['영업이익']

컨센서스   잠정치
2020/06  1000   900
2020/09  1200  1400

In [44]:
df[('영업이익', '컨센서스')]

2020/06    1000
2020/09    1200
Name: (영업이익, 컨센서스), dtype: int64

In [45]:
df.loc['2020/06', '영업이익']

컨센서스    1000
잠정치      900
Name: 2020/06, dtype: int64

In [46]:
print(df.transpose())
print(df.T)

            2020/06  2020/09
영업이익  컨센서스     1000     1200
      잠정치       900     1400
당기순이익 컨센서스      800      900
      잠정치       700      800
            2020/06  2020/09
영업이익  컨센서스     1000     1200
      잠정치       900     1400
당기순이익 컨센서스      800      900
      잠정치       700      800


In [49]:
from pandas import DataFrame
import pandas as pd

data = [
    [1000, 900, 800, 700],
    [1200, 1400, 900, 800],
]

level_0 = ['영업이익', '당기순이익']
level_1 = ['컨센서스', '잠정치']
columns = pd.MultiIndex.from_product([level_0, level_1])

df = DataFrame(data=data, index=['2020/06', '2020/09'], columns=columns)
print(df.stack())

              당기순이익  영업이익
2020/06 잠정치     700   900
        컨센서스    800  1000
2020/09 잠정치     800  1400
        컨센서스    900  1200


In [50]:
df.stack(level=0)

잠정치  컨센서스
2020/06 당기순이익   700   800
        영업이익    900  1000
2020/09 당기순이익   800   900
        영업이익   1400  1200

In [51]:
df.stack().stack()

2020/06  잠정치   당기순이익     700
               영업이익      900
         컨센서스  당기순이익     800
               영업이익     1000
2020/09  잠정치   당기순이익     800
               영업이익     1400
         컨센서스  당기순이익     900
               영업이익     1200
dtype: int64

In [52]:
df.stack().unstack

<bound method DataFrame.unstack of               당기순이익  영업이익
2020/06 잠정치     700   900
        컨센서스    800  1000
2020/09 잠정치     800  1400
        컨센서스    900  1200>

In [56]:
data = [
    [1000,1100,900,1200,1300],
    [800,2000,1700,1500,1800]
    
]

index = ['자본금', '부채']
columns = ['2020/03', '2020/06', '2020/09' ,'2021/03', '2021/06']
df = DataFrame(data, index, columns)

In [57]:
df_stacked = df.stack().reset_index()

In [58]:
temp = df_stacked['level_1'].str.split('/')
print(temp)

0    [2020, 03]
1    [2020, 06]
2    [2020, 09]
3    [2021, 03]
4    [2021, 06]
5    [2020, 03]
6    [2020, 06]
7    [2020, 09]
8    [2021, 03]
9    [2021, 06]
Name: level_1, dtype: object


In [60]:
df_split = DataFrame(list(df_stacked['level_1'].str.split('/')))

In [61]:
df_merged = pd.concat( [ df_stacked, df_split],axis=1)
df_merged.columns = ['계정', '년월', '금액', '연도', '월']
print(df_merged)

    계정       년월    금액    연도   월
0  자본금  2020/03  1000  2020  03
1  자본금  2020/06  1100  2020  06
2  자본금  2020/09   900  2020  09
3  자본금  2021/03  1200  2021  03
4  자본금  2021/06  1300  2021  06
5   부채  2020/03   800  2020  03
6   부채  2020/06  2000  2020  06
7   부채  2020/09  1700  2020  09
8   부채  2021/03  1500  2021  03
9   부채  2021/06  1800  2021  06


In [62]:
df_group = df_merged.groupby(['계정', "연도"]).sum()

In [63]:
df_group

금액
계정  연도        
부채  2020  4500
    2021  3300
자본금 2020  3000
    2021  2500

In [64]:
df_unstack = df_group.unstack()
result = df_unstack('금액')
result.columns.name =''
result.index.name=''
print(result)

TypeError: 'DataFrame' object is not callable

In [65]:
from pandas import DataFrame
import pandas as pd

data = [
    ['2021-08-12', '삼성전자', 77000],
    ['2021-08-13', '삼성전자', 74400],
    ['2021-08-12', 'LG전자', 153000],
    ['2021-08-13', 'LG전자', 150500],
    ['2021-08-13', 'SK하이닉스', 100500],
    ['2021-08-13', 'SK하이닉스', 101500],
    
]
columns = ["날짜", '종목명', '종가']
df = DataFrame(data=data, columns=columns)
df

날짜     종목명      종가
0  2021-08-12    삼성전자   77000
1  2021-08-13    삼성전자   74400
2  2021-08-12    LG전자  153000
3  2021-08-13    LG전자  150500
4  2021-08-13  SK하이닉스  100500
5  2021-08-13  SK하이닉스  101500

In [66]:
pd.pivot(data=df, index="날짜", columns="종목명", values="종가")

ValueError: Index contains duplicate entries, cannot reshape